In [1]:
import pandas as pd

In [2]:
df= pd.read_csv("WELFake_Dataset.csv")

In [3]:
df

,Unnamed: 0,title,text,label
0,0,LAW ENFORCEMENT ON HIGH ALERT Following Threat...,No comment is expected from Barack Obama Membe...,1
1,1,NaN,Did they post their votes for Hillary already?,1
2,2,UNBELIEVABLE! OBAMA’S ATTORNEY GENERAL SAYS MO...,"Now, most of the demonstrators gathered last ...",1
3,3,"Bobby Jindal, raised Hindu, uses story of Chri...",A dozen politically active pastors came here f...,0
4,4,SATAN 2: Russia unvelis an image of its terrif...,"The RS-28 Sarmat missile, dubbed Satan 2, will...",1
...,...,...,...,...
72129,72129,Russians steal research on Trump in hack of U....,WASHINGTON (Reuters) - Hackers believed to be ...,0
72130,72130,WATCH: Giuliani Demands That Democrats Apolog...,"You know, because in fantasyland Republicans n...",1
72131,72131,Migrants Refuse To Leave Train At Refugee Camp...,Migrants Refuse To Leave Train At Refugee Camp...,0
72132,72132,Trump tussle gives unpopular Mexican leader mu...,MEXICO CITY (Reuters) - Donald Trump’s combati...,0
72133,72133,Goldman Sachs Endorses Hillary Clinton For Pre...,Goldman Sachs Endorses Hillary Clinton For Pre...,1

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 72134 entries, 0 to 72133
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  72134 non-null  int64
 1   title       71576 non-null  object
 2   text        72095 non-null  object
 3   label       72134 non-null  int64
dtypes: int64(2), object(2)
memory usage: 2.2+ MB

In [5]:
df.isnull().sum()

Unnamed: 0      0
title         558
text           39
label           0
dtype: int64

In [6]:
df['content'] = df['title'] + " " + df['text']

In [7]:
df.shape

(72134, 5)

In [8]:
df.loc[10]

Unnamed: 0                                                   10
title          GOP Senator Just Smacked Down The Most Puncha...
text          The most punchable Alt-Right Nazi on the inter...
label                                                         1
content        GOP Senator Just Smacked Down The Most Puncha...
Name: 10, dtype: object

In [9]:
df1 = df.dropna().copy()

In [10]:
df1.shape

(71537, 5)

In [11]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 71537 entries, 0 to 72133
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  71537 non-null  int64
 1   title       71537 non-null  object
 2   text        71537 non-null  object
 3   label       71537 non-null  int64
 4   content     71537 non-null  object
dtypes: int64(2), object(3)
memory usage: 3.3+ MB

In [12]:
import re

def clean_text(text):
    text = text.lower()
    text = re.sub(r'[^a-zA-Z ]', '', text)
    return text

df1['content'] = df1['content'].apply(clean_text)

In [13]:
df1 = df1.drop(columns=['title','text'])

In [14]:
print(df1.sample())

       Unnamed: 0  label                                            content
54538       54538      0  iran rejects us demand for un visit to militar...

In [15]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(
    max_features=5000,
    stop_words='english',
    ngram_range=(1,2)
)

X = vectorizer.fit_transform(df1['content'])

In [16]:
y = df1['label']

In [17]:
from sklearn.model_selection import train_test_split

In [18]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42
)

In [19]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()
model.fit(X_train, y_train)

LogisticRegression()

In [20]:
from sklearn.metrics import accuracy_score

y_pred = model.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))

Accuracy: 0.9508666480290746

In [21]:
import pickle

pickle.dump(model, open("model.pkl", "wb"))
pickle.dump(vectorizer, open("vectorizer.pkl", "wb"))

In [22]:
df1.columns

Index(['Unnamed: 0', 'label', 'content'], dtype='object')

In [26]:
pd.set_option('display.max_colwidth', None)
df1['label'].value_counts()

label
1    36509
0    35028
Name: count, dtype: int64

In [31]:
df1.tail()

       Unnamed: 0  label  \
72129       72129      0
72130       72130      1
72131       72131      0
72132       72132      0
72133       72133      1

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           content
72129  russians steal research on trump in hack of us democratic party washington reuters  hackers believed to be working for the russian government broke into the democratic national committees computer network spied on internal communications and accessed research on presumptive republican presidential nominee donald trump the committee and security experts said on tuesday two separate groups entered the dncs system and one read email and chat communications for nearly a year before being detected according to the committee and crowdstrike the cyber firm that helped clean up the breach russian spies also targeted the networks of trump and democratic presidential candidate hillary clinton as well as the computers of some republican political action committees the washington post quoted us officials as saying although details were not available a clinton campaign official said there was no evidence the campaigns information systems had been hacked a russian government spokesman denied involvement in the breach i completely rule out a possibility that the russian government or the government bodies have been involved in this dmitry peskov a kremlin spokesman told reuters in moscow the intrusion is emblematic of the sophistication of russian hackers who intelligence officials have long viewed as the most talented of us adversaries in cyberspace the democratic party had been aware of efforts to hack trump material for two months and us intelligence agencies were involved in efforts to find out who was behind the hacking a source familiar with trump opposition research said the source said democratic party operatives believed the hacking was conducted by the russian government the research includes material on trumps business efforts in azerbaijan georgia serbia and russia according to information made available to reuters         cyber attacks against political candidates and organizations are common worldwide us national intelligence director james clapper said last month he was aware of attempted hacks on campaigns and related groups and he expected to see more as the nov  presidential election nears us representative jim langevin a democrat and cofounder of the congressional cybersecurity caucus said it was disconcerting that independent groups penetrated the dnc and that one was able to stay embedded for nearly a year but the groups are extremely sophisticated langevin said and have previously been implicated on attacks at the white house the state department and the german bundestag as well as a number of private companies the dnc contacted crowdstrike in may and within  hours it began investigating unusual activity on the groups network said dmitri alperovitch the companys cofounder and chief technology officer it identified two hacking groups and both were kicked out this weekend he said the first which crowdstrike named cozy bear entered the dncs systems last summer according to the firm it primarily monitored email and chat conversations and may be working for russias federal security service or fsb alperovitch said  russian president vladimir putin once ran the fsb the second group nicknamed fancy bear is probably working on behalf of russias military alperovitch said it gained entry in late april and went straight to the oppo research  on donald trump and exfiltrated some of it he said alperovitch said both groups were among the best threat actors that weve ever encountered but they did not appear to be working together he was not sure how the intrusions occurred but suspected the hackers may have leveraged spearphishing emails to trick dnc employees into downloading malicious code onto their network when we discovered the intrusion we treated this like the serious incident it is rep debbie wasserman schultz chairwoman of the dnc said in a statement our team moved as quickly as possible to kick out the intruders and secure our network trumps interest in russia goes back to the s with a  vanity fair article citing news program appearances in which trump offered his own services as a negotiator with russia  information made available to reuters indicates trump tried on at least three occasions  in   and   to get involved in business deals in russia in  he and an azerbaijanirussian oligarch aras agalarov jointly put on a miss universe competition in moscow and trump was photographed with agalarovs wife son and daughter the last two us presidential cycles in  and  witnessed a barrage of cyber attacks from a range of adversaries targeting president barack obamas campaign and the campaigns of his republican foes us intelligence officials have said many previous assaults were linked to chinese hackers
72130                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  watch giuliani demands that democrats apologize for trumps racist birtherism you know because in fantasyland republicans never questioned the citizenship of america s first black presidentbut that s exactly what they did for years and donald trump led the charge by going on or calling into fox news every chance he could in order to demand president obama s birth certificateit was trump who constantly claimed president obama was born in kenya even though hawaii newspapers from the time announce obama s birthtrump and his birther fans were finally utterly humiliated when president obama released his birth certificate to the publicand now that birtherism is coming back to bite trump on the ass as he tries to convince black voters that he isn t a racistpart of the reason why black voters reject trump is because he questioned the citizenship of president obama simply because he is black but trump wants everyone to pretend he didn t say any nasty things about president obama and trump pawn rudy giuliani is demanding that democrats apologize for trump s birtherismgiuliani who has taken to forgetting about  recently appeared on cnn with jake tapper on sunday and was grilled because trump has not apologized for his birtherism many africanamericans say they are still troubled by mr trump having suggested over and over falsely that the first africanamerican president was born in africa and thus ineligible to be president  tapper begangiuliani immediately blamed hillary clinton for starting the birther conspiracy but tapper quickly factchecked giuliani which forced him to blame clinton s campaign insteadgiuliani then attempted to portray trump as a hero for  resolving  the conspiracy claiming that black people  have a faulty memory he literally thinks black people should thank trump for being a birtherbut tapper was quick to remind giuliani that it was president obama who resolved the conspiracy by releasing his birth certificate in  while trump was still pushing his birtherism four years later in february  when he told cpac that he thinks the birth certificate is fake so apparently trump thinks it hasn t been resolved thus blowing giuliani s claim out of the water should he just apologize for this if he really wants to reach out to minority voters  tapper askedgiuliani replied by demanding that democrats apologize for calling trump s birtherism racist and went on to bash president obama if everybody apologized for all the things they said in politics all we would be doing on television shows is apologizing maybe all the democrats should apologize for calling donald trump a racist and calling him all kinds of terrible names and it gets a little silly food stamps have gone up two and a half times under barack obama  he added  he should be ashamed of himself jobs should have gone up two and a half times my only point is that many africanamericans are still mad about donald trump having tried to invalidate barack obama by claiming he was born in africa  tapper responded before giving up and moving onhere s the video via youtubegiuliani seems to be forgetting that the recession that began under george w bush and the republicans in  caused more families to need food stamps in the first place which is why the number of people on food stamps has gone up also president obama has set a record for the most consecutive months of jobs created and is actually one of the best jobcreating presidents over the last  yearsonce again giuliani gets caught talking out of his ass and he must be truly desperate if he is resorting to demanding an apology from democrats for trump s racismfeatured image screenshot
72131                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        migrants refuse to leave train at refugee camp in hungary migrants refuse to leave train at refugee camp in hungarythousands of migrants flooded into a train station in the hungarian capital thursday after police lifted a twoday blockade but some who boarded a train they thought was going to germany ended up instead at a refugee camp just miles from budapestthe associated press reports that excited migrants piled into a newly arrived train at the keleti station in hungarys capital despite announcements in hungarian and english that all services from the station to western europe had been canceled a statement on the main departures board said no more trains to austria or germany would depart due to safety reasons until further noticemany migrants who couldnt understand either language and were receiving no advice from hungarian officials scrambled aboard in a standingroomonly crush and hoped for the best the ap saidscuffles broke out when police ordered the passengers off the train at bicske according to the bbcmeanwhile hungarys prime minister says his country is doing all it can to manage a growing migrant crisis even as european officials said they will meet this month in brussels to discuss an effort to strengthen the european response to the situationviktor orban said the influx of refugees into his country is really a german problem because that is the intended destination for most of them hungarians along with other europeans are full of fear he says because they see that the european leaders among them the prime ministers are not able to control the situationif we would create an image  just come because we are ready to accept everybody that would be a moral failure because that is not the case orban said after a meeting with european parliament president martin schulz according to the washington post the moral human thing is to make clear please dont come why do you have to go from turkey to europe turkey is a safe country stay there its risky to comemeanwhile voice of america reports that british french and german officials have called for urgent action and plan to hold talks on sept  in brussels to address the crisisvoa reports the three ministers also called for better processing of migrants in italy and greeceas weve reported the united nations believes that more than  migrants have set out for europe from north africa and the middle east on the mediterranean sea so far this year a  percent increase on all of last yearas nprs middle east editor larry kaplow writes on any given day now hundreds of people perhaps thousands are drifting in ships or clinging to boats that are little more than inflatable rafts they go in other ways too jumping fences in morocco to get to spanish territory cramming into trucks from turkey riding trains across europe